name: 清理Workflow和Releases
on:
  workflow_dispatch:

  schedule:
    - cron: 53 16 * * 3

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: 清理Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 0

      - name: 清理Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.token_release }}
