name: 清理Workflow和Releases
on:
  workflow_dispatch:

  schedule:
    - cron: 53 16 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: 清理Workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.token_release }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 2
          retain_days: 15

      - name: 清理Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 15
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.token_release }}
